# Generated by Django 5.1.2 on 2024-10-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recent_login', models.DateTimeField()),
                ('courses_enrolled', models.IntegerField()),
                ('interactions', models.IntegerField()),
            ],
        ),
    ]
